In [3]:
import tensorflow as tf
n_inputs = 3
n_neurons = 5

X0 = tf.placeholder(tf.float32, [None, n_inputs])
X1 = tf.placeholder(tf.float32, [None, n_inputs])

Wx = tf.Variable(tf.random_normal(shape=[n_inputs, n_neurons],dtype=tf.float32))
Wy = tf.Variable(tf.random_normal(shape=[n_neurons,n_neurons],dtype=tf.float32))
b = tf.Variable(tf.zeros([1, n_neurons], dtype=tf.float32))

Y0 = tf.tanh(tf.matmul(X0, Wx) + b)
Y1 = tf.tanh(tf.matmul(Y0, Wy) + tf.matmul(X1, Wx) + b)

init = tf.global_variables_initializer()


In [11]:
import numpy as np
# Mini-batch:        instance 0,instance 1,instance 2,instance 3
X0_batch = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 0, 1]]) # t = 0
X1_batch = np.array([[9, 8, 7], [0, 0, 0], [6, 5, 4], [3, 2, 1]]) # t = 1
with tf.Session() as sess:
    init.run()
    Y0_val, Y1_val = sess.run([Y0, Y1], feed_dict={X0: X0_batch, X1: X1_batch})

In [12]:
print(Y0_val)

[[-1.          0.3151941  -1.         -1.          0.99999821]
 [ 0.          0.          0.          0.          0.        ]
 [-1.          0.31799638 -1.         -0.99999982  0.99991059]
 [-0.99998617  0.3207933  -0.99999219 -0.99129534  0.99532211]]


In [13]:
print(Y1_val)

[[-1.          0.79950899 -1.         -1.          1.        ]
 [ 0.          0.          0.          0.          0.        ]
 [-1.          0.80151218 -1.         -0.99999928  0.99999982]
 [-0.99998993  0.8027904  -0.99999988 -0.97093403  0.9999851 ]]
