In [5]:
import tensorflow as tf
n_inputs = 3
n_neurons = 5

X0 = tf.placeholder(tf.float32, [None, n_inputs])
X1 = tf.placeholder(tf.float32, [None, n_inputs])

Wx = tf.Variable(tf.random_normal(shape=[n_inputs, n_neurons],dtype=tf.float32))
Wy = tf.Variable(tf.random_normal(shape=[n_neurons,n_neurons],dtype=tf.float32))
b = tf.Variable(tf.zeros([1, n_neurons], dtype=tf.float32))

Y0 = tf.tanh(tf.matmul(X0, Wx) + b)
Y1 = tf.tanh(tf.matmul(Y0, Wy) + tf.matmul(X1, Wx) + b)

init = tf.global_variables_initializer()

import numpy as np
# Mini-batch:        instance 0,instance 1,instance 2,instance 3
X0_batch = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 0, 1]]) # t = 0
X1_batch = np.array([[9, 8, 7], [0, 0, 0], [6, 5, 4], [3, 2, 1]]) # t = 1
with tf.Session() as sess:
    init.run()
    Y0_val, Y1_val = sess.run([Y0, Y1], feed_dict={X0: X0_batch, X1: X1_batch})

In [6]:
print(Y0_val)

[[-0.99075651  0.99936646  0.74387997  0.73116761 -0.82016903]
 [-0.99999994  1.          0.95165676  0.97256529 -0.97153622]
 [-1.          1.          0.99167931  0.99751174 -0.99578953]
 [-0.99989128  0.99999136 -0.10039877 -0.96698606  1.        ]]


In [7]:
print(Y1_val)

[[-1.          1.          0.95380259  0.99332684 -0.99724996]
 [-0.4774189  -0.93510967  0.45376167 -0.09377933 -0.97654808]
 [-1.          1.          0.87824225  0.87659311 -0.99553168]
 [-0.9991625   0.9689635  -0.98562509  0.99702954  0.99537408]]


In [8]:
arr = np.array([1,2,3,4,5])
arr += 1

In [9]:
arr

array([2, 3, 4, 5, 6])

In [10]:
X0 = tf.placeholder(tf.float32, [None, n_inputs])
X1 = tf.placeholder(tf.float32, [None, n_inputs])
basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
output_seqs, states = tf.contrib.rnn.static_rnn(
                        basic_cell, [X0, X1], dtype=tf.float32)
Y0, Y1 = output_seqs

In [11]:
print(Y0)


Tensor("rnn/basic_rnn_cell/Tanh:0", shape=(?, 5), dtype=float32)
