In [2]:
import pandas as pd
import numpy as np
arr = np.array([1,2,3,4,5])
index = (arr==3)
type(index)

numpy.ndarray

In [20]:
arr = np.arange(100).reshape((10,10))
np.argmax(arr, 1)

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [21]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [24]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(10) == arr[:, None]

array([[ True, False, False, False, False, False, False, False, False,
        False],
       [False,  True, False, False, False, False, False, False, False,
        False],
       [False, False,  True, False, False, False, False, False, False,
        False],
       [False, False, False,  True, False, False, False, False, False,
        False],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [False, False, False, False, False,  True, False, False, False,
        False],
       [False, False, False, False, False, False,  True, False, False,
        False],
       [False, False, False, False, False, False, False,  True, False,
        False],
       [False, False, False, False, False, False, False, False,  True,
        False],
       [False, False, False, False, False, False, False, False, False,
         True]], dtype=bool)

In [6]:
arr[index]

array([3])

In [7]:
print(arr[index])

[3]


In [8]:
print(arr[i2])

[3]


In [10]:
print(arr[[2,1,3,4,0]])


[3 2 4 5 1]


In [11]:
arr2 = [0,1,2,3,4]
print(arr2[[0,1,2,4,3]])

TypeError: list indices must be integers, not list

In [22]:
import random
for i in range(1,10,2):
    print(random.randint(1,10))

3
1
8
7
6


In [25]:
from Tkinter import *
root=Tk()
label = Label(root, text="I am a label widget")
button = Button(root, text="I am a button")
label.pack()
button.pack()
root.mainloop()
count = input("횟수 입력하세요")

횟수 입력하세요1


In [29]:
1%2 == 0

False

In [27]:
28//4

7

In [35]:
import requests
url = 'https://www.google.com'
r = requests.get(url)
print(r.text)

<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="ko"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script>(function(){window.google={kEI:'DcvlWNCeEYif8QXczK2gBQ',kEXPI:'1351892,1352468,1352864,1352994,1353038,1353106,3700264,3700347,3700405,4029370,4029815,4031109,4032678,4036527,4039268,4043492,4045841,4048347,4063965,4064904,4065786,4066196,4072364,4072777,4076096,4076999,4078430,4078760,4081039,4081165,4083458,4084180,4089338,4090550,4090553,4090806,4092627,4092934,4093082,4093313,4093484,4093497,4093791,4094251,4094544,4094832,4095574,4095910,4095997,4096323,4097153,4097203,4097922,4097929,4098051,4098600,4098733,4098740,4098752,4099764,4100169,4100379,4100827,4101050,4101376,4101654,4101684,4102237,4102411,4102658,4102689,4102987,4103167,4103254,4103475,4103849,4103999,4104057,4104063,4104158,4104197,4104290,4104

In [36]:
ls

Test.ipynb       pydata/          tf-udacity-pyml/
a.out*           test.cpp


In [37]:
mkdir "test"

In [38]:
ls

Test.ipynb       pydata/          test.cpp
a.out*           test/            tf-udacity-pyml/


In [ ]:
ls

In [ ]:
import glob
files = glob.glob('./*.py')

In [ ]:
files

In [ ]:
sum2  = 100
print "9에서 12까지의 정수 합계는 ", sum2, "이다"

In [6]:
for number in range(1, 101, 1):
    if number == 2: #2는 소수이므로 바로 출력
        print number
    for x in range(2,number): #2부터 number-1까지 나누어 본다
        if number % x == 0: #나누어 떨어지면 소수가 아니므로 break
            break
        elif x == number - 1: #number-1까지 나누어지지 않으면 소수
            print number


2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97


In [9]:
class Ainput:
    def __init__(self, a, b):
        self.a = a
        self.b = b
    def printnum(self):
        print("첫번째 숫자: ", self.a)
        print("두번째 숫자: ", self.b)

class Calculator(Ainput):
    def __init__(self, a, b):
        self.a = a
        self.b = b
    def start(self, a, b):
        a = input("첫번째 숫자: ")
        b = input("두번째 숫자: ")
    def add(self, a, b):
        result = a + b
        print(result)

    def sub(self, a, b):
        result = a - b
        print(result)

    def multiply(self, a, b):
        result = a * b
        print(result)

    def divide(self, a, b):
        if a == 0 or b == 0:
            print("Error")
            return
        result = a / b
        print(result)
        
calc = Calculator()
calc.start(, a, b)
print("  Menu  ")
print("--------")
print(" 1: add ")
print(" 2: sub ")
print(" 3: multiply")
print(" 4: divide")
print(" 5: stop")
sel = int(input(":"))

if(sel == 1):
    add()
elif(sel == 2):
   sub()
elif(sel == 3):
   multiply()
elif(sel == 4):
    divide()

else:
    print("Wrong input, please input again")


NameError: name 'start' is not defined

In [17]:
student = '현재\n'
print student, "haha"

현재
haha


In [13]:
arr = student.strip()

In [16]:
print arr, "haha"

현재 haha


In [20]:
import math
math.empty(4, float)

AttributeError: 'module' object has no attribute 'empty'

In [22]:
txt = input("input: ")

input: 1 2 3 4 5 6 


SyntaxError: invalid syntax (<string>, line 1)

In [24]:
count = -1
num = 0
total = 0
while (num != 0):
    num = input(' 숫자 하나씩 입력:')
    total = total + num
    count = count + 1
    if num == 0:
        print('지금 0을 입력했네요. 지금까지 입력된 수는{}개이고 합계는 {}개입니다.' .format (count,sum))

In [26]:
class A:
    def __init__(self):
        pass
    
temp = A()

In [27]:
temp.aagag = 'a'

In [28]:
temp.aagag

'a'

In [29]:
import numpy as np
np.random.seed(0)
X_xor = np.random.randn(200,2)
y_xor = np.logical_xor(X_xor[:,0] > 0, X_xor[:, 1]>0)
y_xor = np.where(y_xor, 1, -1)


In [30]:
y_xor

array([-1, -1,  1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1, -1, -1, -1,
        1, -1, -1, -1,  1, -1,  1, -1,  1, -1,  1, -1, -1, -1, -1,  1,  1,
        1, -1,  1,  1, -1,  1,  1,  1, -1,  1,  1,  1, -1, -1, -1, -1,  1,
        1,  1, -1, -1, -1,  1,  1,  1, -1,  1, -1, -1,  1, -1,  1,  1,  1,
        1,  1,  1, -1, -1,  1, -1,  1, -1, -1,  1, -1,  1, -1,  1, -1, -1,
       -1,  1,  1, -1,  1, -1, -1,  1,  1,  1,  1, -1,  1, -1, -1, -1, -1,
        1, -1,  1, -1,  1, -1,  1,  1, -1,  1,  1, -1, -1, -1,  1,  1,  1,
       -1, -1, -1, -1, -1, -1,  1,  1, -1, -1,  1, -1, -1,  1, -1,  1,  1,
       -1, -1,  1,  1,  1,  1, -1,  1, -1, -1,  1,  1, -1,  1,  1, -1,  1,
       -1,  1,  1, -1,  1, -1, -1, -1,  1, -1,  1,  1,  1,  1,  1,  1,  1,
        1, -1, -1,  1, -1, -1,  1, -1, -1,  1, -1, -1,  1, -1, -1,  1,  1,
       -1,  1,  1,  1, -1,  1, -1, -1,  1, -1, -1, -1, -1])

In [31]:
y_xor[y_xor==1].sum()

101

In [32]:
y_xor[y_xor==-1].sum()

-99

In [37]:
import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.close_figures = False

In [38]:
X_xor = np.random.randn(200,2)

In [41]:
X_xor[:,0].mean()

-0.1074597310949032

In [42]:
X_xor[:,1].mean()

-0.12956232361266534

In [43]:
X_xor.mean()

-0.11851102735378427

In [44]:
X_xor[:,0].std()

0.98083408290717988

In [45]:
X_xor[:,1].std()

1.0239086228873744

In [46]:
X_xor.std()

1.0026636097200026

In [47]:
X_xor[:, 0]

array([-0.59865394,  0.76666318, -1.76853845,  0.81451982, -0.18505367,
       -1.4465347 , -0.30911444,  1.73272119,  0.370825  ,  1.51999486,
        0.92950511, -2.09460307, -0.13010695,  0.94304609, -0.56931205,
       -0.46684555,  0.86896349, -0.97110457,  0.82158571,  0.8005648 ,
       -0.39522898, -0.08593077,  0.87583276,  0.45741561, -0.78262916,
       -1.05462846,  0.46313033,  0.33890413, -0.46886419,  0.1993002 ,
       -0.51751904, -0.43918952, -0.5028167 , -0.96050438, -2.28862004,
       -2.01640663, -0.27567053,  1.73887268,  1.31913688,  1.12859406,
        0.77140595, -0.90876325,  0.86259601,  1.51332808, -0.04570396,
       -1.02993528,  1.10028434,  2.69622405, -0.65855297, -1.01804188,
        0.38273243,  1.09634685, -0.34745065, -1.63263453, -1.17915793,
        0.89526027, -1.33221165, -0.66005632,  0.49869027,  0.28427967,
       -0.22260568, -1.68121822,  0.24211796,  0.93674246, -2.36958691,
       -2.23960406,  1.22487056, -1.27968917, -0.26164545, -0.20

In [48]:
X_xor[:, 1]

array([ -1.11589699e+00,   3.56292817e-01,   3.55481793e-01,
         5.89255892e-02,  -8.07648488e-01,   8.00297949e-01,
        -2.33466662e-01,   6.84501107e-01,   1.42061805e-01,
         1.71958931e+00,   5.82224591e-01,   1.23721914e-01,
         9.39532294e-02,  -2.73967717e+00,   2.69904355e-01,
        -1.41690611e+00,   2.76871906e-01,   3.14817205e-01,
         5.29264630e-03,   7.82601752e-02,  -1.15942052e+00,
         1.94292938e-01,  -1.15107468e-01,  -9.64612014e-01,
        -1.10389299e-01,   8.20247837e-01,   2.79095764e-01,
         2.02104356e+00,  -2.20144129e+00,  -5.06035410e-02,
        -9.78829859e-01,   1.81338429e-01,   2.41245368e+00,
        -7.93117363e-01,   2.51484415e-01,  -5.39454633e-01,
        -7.09727966e-01,   9.94394391e-01,  -8.82418819e-01,
         4.96000946e-01,   1.02943883e+00,  -4.24317621e-01,
        -2.65561909e+00,   5.53132064e-01,   2.20507656e-01,
        -3.49943365e-01,   1.29802197e+00,  -7.39246663e-02,
        -5.14233966e-01,